var MEGA_EVO_DATA = [
  {id:460,name:'abomasnow',megaName:'Mega Abomasnow',types:['grass','ice'],ability:'snow-warning',bst:594,stone:'Abomasite',sdn:'abomasnowmega',fid:10060},
  {id:359,name:'absol',megaName:'Mega Absol',types:['dark'],ability:'magic-bounce',bst:565,stone:'Absolite',sdn:'absolmega',fid:10057},
  {id:142,name:'aerodactyl',megaName:'Mega Aerodactyl',types:['rock','flying'],ability:'tough-claws',bst:615,stone:'Aerodactylite',sdn:'aerodactylmega',fid:10042},
  {id:306,name:'aggron',megaName:'Mega Aggron',types:['steel'],ability:'filter',bst:630,stone:'Aggronite',sdn:'aggronmega',fid:10053},
  {id:65,name:'alakazam',megaName:'Mega Alakazam',types:['psychic'],ability:'trace',bst:600,stone:'Alakazite',sdn:'alakazammega',fid:10037},
  {id:334,name:'altaria',megaName:'Mega Altaria',types:['dragon','fairy'],ability:'pixilate',bst:590,stone:'Altarianite',sdn:'altariamega',fid:10067},
  {id:181,name:'ampharos',megaName:'Mega Ampharos',types:['electric','dragon'],ability:'mold-breaker',bst:610,stone:'Ampharosite',sdn:'ampharosmega',fid:10045},
  {id:531,name:'audino',megaName:'Mega Audino',types:['normal','fairy'],ability:'healer',bst:545,stone:'Audinite',sdn:'audinomega',fid:10069},
  {id:354,name:'banette',megaName:'Mega Banette',types:['ghost'],ability:'prankster',bst:555,stone:'Banettite',sdn:'banettemega',fid:10056},
  {id:689,name:'barbaracle',megaName:'Mega Barbaracle',types:['rock','fighting'],ability:'tough-claws',bst:600,stone:'Mega Barbaracle Stone',sdn:'barbaraclemega',fid:10298},
  {id:908,name:'meowscarada',megaName:'Mega Meowscarada',types:['dragon','ice'],ability:'unknown',bst:700,stone:'Mega Meowscarada Stone',sdn:'meowscaradamega',fid:10325},
  {id:15,name:'beedrill',megaName:'Mega Beedrill',types:['bug','poison'],ability:'adaptability',bst:495,stone:'Beedrillite',sdn:'beedrillmega',fid:10090},
  {id:9,name:'blastoise',megaName:'Mega Blastoise',types:['water'],ability:'mega-launcher',bst:630,stone:'Blastoisinite',sdn:'blastoisemega',fid:10036},
  {id:257,name:'blaziken',megaName:'Mega Blaziken',types:['fire','fighting'],ability:'speed-boost',bst:630,stone:'Blazikenite',sdn:'blazikenmega',fid:10050},
  {id:323,name:'camerupt',megaName:'Mega Camerupt',types:['fire','ground'],ability:'sheer-force',bst:560,stone:'Cameruptite',sdn:'cameruptmega',fid:10087},
  {id:609,name:'chandelure',megaName:'Mega Chandelure',types:['ghost','fire'],ability:'infiltrator',bst:620,stone:'Mega Chandelure Stone',sdn:'chandeluremega',fid:10291},
  {id:6,name:'charizard',megaName:'Mega Charizard',types:['fire','dragon'],ability:'tough-claws',bst:634,stone:'Charizardite',sdn:'charizardmega',fid:10034},
  {id:6,name:'charizard',megaName:'Mega Charizard',types:['fire','flying'],ability:'drought',bst:634,stone:'Charizardite',sdn:'charizardmega',fid:10035},
  {id:652,name:'chesnaught',megaName:'Mega Chesnaught',types:['grass','fighting'],ability:'bulletproof',bst:630,stone:'Mega Chesnaught Stone',sdn:'chesnaughtmega',fid:10292},
  {id:358,name:'chimecho',megaName:'Mega Chimecho',types:['psychic','steel'],ability:'levitate',bst:555,stone:'Mega Chimecho Stone',sdn:'chimechomega',fid:10306},
  {id:35,name:'clefairy',megaName:'Mega Clefairy',types:['fairy','flying'],ability:'magic-bounce',bst:583,stone:'Mega Clefairy Stone',sdn:'clefairymega',fid:10278},
  {id:740,name:'crabominable',megaName:'Mega Crabominable',types:['fighting','ice'],ability:'iron-fist',bst:578,stone:'Mega Crabominable Stone',sdn:'crabominablemega',fid:10315},
  {id:491,name:'darkrai',megaName:'Mega Darkrai',types:['dark'],ability:'unknown',bst:700,stone:'Mega Darkrai Stone',sdn:'darkraimega',fid:10312},
  {id:653,name:'fennekin',megaName:'Mega Fennekin',types:['fire','psychic'],ability:'levitate',bst:634,stone:'Mega Fennekin Stone',sdn:'fennekinmega',fid:10293},
  {id:719,name:'diancie',megaName:'Mega Diancie',types:['rock','fairy'],ability:'magic-bounce',bst:700,stone:'Diancite',sdn:'dianciemega',fid:10075},
  {id:691,name:'dragalge',megaName:'Mega Dragalge',types:['poison','dragon'],ability:'regenerator',bst:594,stone:'Mega Dragalge Stone',sdn:'dragalgemega',fid:10299},
  {id:149,name:'dragonite',megaName:'Mega Dragonite',types:['dragon','flying'],ability:'multiscale',bst:700,stone:'Mega Dragonite Stone',sdn:'dragonitemega',fid:10281},
  {id:776,name:'turtonator',megaName:'Mega Turtonator',types:['normal','dragon'],ability:'berserk',bst:585,stone:'Mega Turtonator Stone',sdn:'turtonatormega',fid:10302},
  {id:644,name:'zekrom',megaName:'Mega Zekrom',types:['electric'],ability:'eelevate',bst:615,stone:'Mega Zekrom Stone',sdn:'zekrommega',fid:10290},
  {id:500,name:'emboar',megaName:'Mega Emboar',types:['fire','fighting'],ability:'mold-breaker',bst:628,stone:'Mega Emboar Stone',sdn:'emboarmega',fid:10286},
  {id:530,name:'excadrill',megaName:'Mega Excadrill',types:['ground','steel'],ability:'piercing-drill',bst:608,stone:'Mega Excadrill Stone',sdn:'excadrillmega',fid:10287},
  {id:876,name:'indeedee-male',megaName:'Mega Indeedee-male',types:['fighting'],ability:'defiant',bst:570,stone:'Mega Indeedee-male Stone',sdn:'indeedee-malemega',fid:10303},
  {id:160,name:'feraligatr',megaName:'Mega Feraligatr',types:['water','dragon'],ability:'dragonize',bst:630,stone:'Mega Feraligatr Stone',sdn:'feraligatrmega',fid:10283},
  {id:670,name:'floette',megaName:'Mega Floette',types:['fairy'],ability:'fairy-aura',bst:651,stone:'Mega Floette Stone',sdn:'floettemega',fid:10296},
  {id:478,name:'froslass',megaName:'Mega Froslass',types:['ice','ghost'],ability:'snow-warning',bst:580,stone:'Mega Froslass Stone',sdn:'froslassmega',fid:10285},
  {id:475,name:'gallade',megaName:'Mega Gallade',types:['psychic','fighting'],ability:'inner-focus',bst:618,stone:'Galladite',sdn:'gallademega',fid:10068},
  {id:445,name:'garchomp',megaName:'Mega Garchomp',types:['dragon','ground'],ability:'sand-force',bst:700,stone:'Mega Garchomp Stone',sdn:'garchompmega',fid:10058},
  {id:282,name:'gardevoir',megaName:'Mega Gardevoir',types:['psychic','fairy'],ability:'pixilate',bst:618,stone:'Gardevoirite',sdn:'gardevoirmega',fid:10051},
  {id:94,name:'gengar',megaName:'Mega Gengar',types:['ghost','poison'],ability:'shadow-tag',bst:600,stone:'Gengarite',sdn:'gengarmega',fid:10038},
  {id:362,name:'glalie',megaName:'Mega Glalie',types:['ice'],ability:'refrigerate',bst:580,stone:'Glalitite',sdn:'glaliemega',fid:10074},
  {id:868,name:'milcery',megaName:'Mega Milcery',types:['rock','poison'],ability:'adaptability',bst:625,stone:'Mega Milcery Stone',sdn:'milcerymega',fid:10321},
  {id:768,name:'golisopod',megaName:'Mega Golisopod',types:['bug','steel'],ability:'unknown',bst:630,stone:'Mega Golisopod Stone',sdn:'golisopodmega',fid:10316},
  {id:623,name:'golurk',megaName:'Mega Golurk',types:['ground','ghost'],ability:'unseen-fist',bst:583,stone:'Mega Golurk Stone',sdn:'golurkmega',fid:10313},
  {id:658,name:'greninja',megaName:'Mega Greninja',types:['water','dark'],ability:'protean',bst:630,stone:'Battle Bond',sdn:'greninjamega',fid:10294},
  {id:130,name:'gyarados',megaName:'Mega Gyarados',types:['water','dark'],ability:'mold-breaker',bst:640,stone:'Gyaradosite',sdn:'gyaradosmega',fid:10041},
  {id:701,name:'hawlucha',megaName:'Mega Hawlucha',types:['fighting','flying'],ability:'no-guard',bst:600,stone:'Mega Hawlucha Stone',sdn:'hawluchamega',fid:10300},
  {id:485,name:'heatran',megaName:'Mega Heatran',types:['fire','steel'],ability:'unknown',bst:700,stone:'Mega Heatran Stone',sdn:'heatranmega',fid:10311},
  {id:214,name:'heracross',megaName:'Mega Heracross',types:['bug','fighting'],ability:'skill-link',bst:600,stone:'Heracronite',sdn:'heracrossmega',fid:10047},
  {id:228,name:'houndour',megaName:'Mega Houndour',types:['dark','fire'],ability:'solar-power',bst:600,stone:'Houndoominite',sdn:'houndourmega',fid:10048},
  {id:115,name:'kangaskhan',megaName:'Mega Kangaskhan',types:['normal'],ability:'parental-bond',bst:590,stone:'Kangaskhanite',sdn:'kangaskhanmega',fid:10039},
  {id:380,name:'latias',megaName:'Mega Latias',types:['dragon','psychic'],ability:'levitate',bst:700,stone:'Latiasite',sdn:'latiasmega',fid:10062},
  {id:381,name:'latios',megaName:'Mega Latios',types:['dragon','psychic'],ability:'levitate',bst:700,stone:'Latiosite',sdn:'latiosmega',fid:10063},
  {id:428,name:'lopunny',megaName:'Mega Lopunny',types:['normal','fighting'],ability:'scrappy',bst:580,stone:'Lopunnite',sdn:'lopunnymega',fid:10088},
  {id:448,name:'lucario',megaName:'Mega Lucario',types:['fighting','steel'],ability:'adaptability',bst:625,stone:'Lucarionite',sdn:'lucariomega',fid:10059},
  {id:801,name:'magearna',megaName:'Mega Magearna',types:['steel','fairy'],ability:'unknown',bst:700,stone:'Mega Magearna Stone',sdn:'magearnamega',fid:10317},
  {id:687,name:'malamar',megaName:'Mega Malamar',types:['dark','psychic'],ability:'contrary',bst:582,stone:'Mega Malamar Stone',sdn:'malamarmega',fid:10297},
  {id:310,name:'manectric',megaName:'Mega Manectric',types:['electric'],ability:'intimidate',bst:575,stone:'Manectite',sdn:'manectricmega',fid:10055},
  {id:303,name:'mawile',megaName:'Mega Mawile',types:['steel','fairy'],ability:'huge-power',bst:480,stone:'Mawilite',sdn:'mawilemega',fid:10052},
  {id:308,name:'medicham',megaName:'Mega Medicham',types:['fighting','psychic'],ability:'pure-power',bst:510,stone:'Medichamite',sdn:'medichammega',fid:10054},
  {id:154,name:'meganium',megaName:'Mega Meganium',types:['grass','fairy'],ability:'mega-sol',bst:625,stone:'Mega Meganium Stone',sdn:'meganiummega',fid:10282},
  {id:676,name:'furfrou',megaName:'Mega Furfrou',types:['psychic'],ability:'trace',bst:566,stone:'Mega Furfrou Stone',sdn:'furfroumega',fid:10314},
  {id:676,name:'furfrou',megaName:'Mega Furfrou',types:['psychic'],ability:'trace',bst:566,stone:'Mega Furfrou Stone',sdn:'furfroumega',fid:10326},
  {id:376,name:'metagross',megaName:'Mega Metagross',types:['steel','psychic'],ability:'tough-claws',bst:700,stone:'Metagrossite',sdn:'metagrossmega',fid:10076},
  {id:150,name:'mewtwo',megaName:'Mega Mewtwo',types:['psychic','fighting'],ability:'steadfast',bst:780,stone:'Mewtwonite',sdn:'mewtwomega',fid:10043},
  {id:150,name:'mewtwo',megaName:'Mega Mewtwo',types:['psychic'],ability:'insomnia',bst:780,stone:'Mewtwonite',sdn:'mewtwomega',fid:10044},
  {id:18,name:'pidgeot',megaName:'Mega Pidgeot',types:['normal','flying'],ability:'no-guard',bst:579,stone:'Pidgeotite',sdn:'pidgeotmega',fid:10073},
  {id:127,name:'pinsir',megaName:'Mega Pinsir',types:['bug','flying'],ability:'aerilate',bst:600,stone:'Pinsirite',sdn:'pinsirmega',fid:10040},
  {id:667,name:'litleo',megaName:'Mega Litleo',types:['fire','normal'],ability:'fire-mane',bst:607,stone:'Mega Litleo Stone',sdn:'litleomega',fid:10295},
  {id:26,name:'raichu',megaName:'Mega Raichu',types:['electric'],ability:'electric-surge',bst:585,stone:'Mega Raichu Stone',sdn:'raichumega',fid:10304},
  {id:26,name:'raichu',megaName:'Mega Raichu',types:['electric'],ability:'no-guard',bst:585,stone:'Mega Raichu Stone',sdn:'raichumega',fid:10305},
  {id:384,name:'rayquaza',megaName:'Mega Rayquaza',types:['dragon','flying'],ability:'delta-stream',bst:780,stone:'Dragon Ascent',sdn:'rayquazamega',fid:10079},
  {id:302,name:'sableye',megaName:'Mega Sableye',types:['dark','ghost'],ability:'magic-bounce',bst:480,stone:'Sableyite',sdn:'sableyemega',fid:10066},
  {id:373,name:'salamence',megaName:'Mega Salamence',types:['dragon','flying'],ability:'aerilate',bst:700,stone:'Salamencite',sdn:'salamencemega',fid:10089},
  {id:254,name:'sceptile',megaName:'Mega Sceptile',types:['grass','dragon'],ability:'lightning-rod',bst:630,stone:'Sceptilite',sdn:'sceptilemega',fid:10065},
  {id:212,name:'scizor',megaName:'Mega Scizor',types:['bug','steel'],ability:'technician',bst:600,stone:'Scizorite',sdn:'scizormega',fid:10046},
  {id:545,name:'scolipede',megaName:'Mega Scolipede',types:['bug','poison'],ability:'shell-armor',bst:585,stone:'Mega Scolipede Stone',sdn:'scolipedemega',fid:10288},
  {id:843,name:'silicobra',megaName:'Mega Silicobra',types:['grass','fire'],ability:'spicy-spray',bst:586,stone:'Mega Silicobra Stone',sdn:'silicobramega',fid:10320},
  {id:560,name:'scrafty',megaName:'Mega Scrafty',types:['dark','fighting'],ability:'intimidate',bst:588,stone:'Mega Scrafty Stone',sdn:'scraftymega',fid:10289},
  {id:319,name:'sharpedo',megaName:'Mega Sharpedo',types:['water','dark'],ability:'strong-jaw',bst:560,stone:'Sharpedonite',sdn:'sharpedomega',fid:10070},
  {id:227,name:'skarmory',megaName:'Mega Skarmory',types:['steel','flying'],ability:'stalwart',bst:565,stone:'Mega Skarmory Stone',sdn:'skarmorymega',fid:10284},
  {id:80,name:'slowbro',megaName:'Mega Slowbro',types:['water','psychic'],ability:'shell-armor',bst:590,stone:'Slowbronite',sdn:'slowbromega',fid:10071},
  {id:398,name:'staraptor',megaName:'Mega Staraptor',types:['fighting','flying'],ability:'contrary',bst:585,stone:'Mega Staraptor Stone',sdn:'staraptormega',fid:10308},
  {id:121,name:'starmie',megaName:'Mega Starmie',types:['water','psychic'],ability:'huge-power',bst:620,stone:'Mega Starmie Stone',sdn:'starmiemega',fid:10280},
  {id:208,name:'steelix',megaName:'Mega Steelix',types:['steel','ground'],ability:'sand-force',bst:610,stone:'Steelixite',sdn:'steelixmega',fid:10072},
  {id:260,name:'swampert',megaName:'Mega Swampert',types:['water','ground'],ability:'swift-swim',bst:635,stone:'Swampertite',sdn:'swampertmega',fid:10064},
  {id:248,name:'tyranitar',megaName:'Mega Tyranitar',types:['rock','dark'],ability:'sand-stream',bst:700,stone:'Tyranitarite',sdn:'tyranitarmega',fid:10049},
  {id:3,name:'venusaur',megaName:'Mega Venusaur',types:['grass','poison'],ability:'thick-fat',bst:625,stone:'Venusaurite',sdn:'venusaurmega',fid:10033},
  {id:71,name:'victreebel',megaName:'Mega Victreebel',types:['grass','poison'],ability:'innards-out',bst:590,stone:'Mega Victreebel Stone',sdn:'victreebelmega',fid:10279},
  {id:807,name:'zeraora',megaName:'Mega Zeraora',types:['electric'],ability:'unknown',bst:700,stone:'Mega Zeraora Stone',sdn:'zeraoramega',fid:10319},
  {id:718,name:'zygarde-50',megaName:'Mega Zygarde-50',types:['dragon','ground'],ability:'unknown',bst:778,stone:'Mega Zygarde-50 Stone',sdn:'zygarde-50mega',fid:10301}
];
