var MEGA_EVO_DATA = [
  {id:10060,name:'abomasnow',megaName:'Mega Abomasnow',types:['grass','ice'],ability:'snow-warning',bst:594,stone:'Mega Abomasnow Stone',sdn:'abomasnowmega',fid:10060},
  {id:10057,name:'absol',megaName:'Mega Absol',types:['dark'],ability:'magic-bounce',bst:565,stone:'Mega Absol Stone',sdn:'absolmega',fid:10057},
  {id:10307,name:'absol',megaName:'Mega Absol',types:['dark','ghost'],ability:'unknown',bst:565,stone:'Mega Absol Stone',sdn:'absolmega',fid:10307},
  {id:10042,name:'aerodactyl',megaName:'Mega Aerodactyl',types:['rock','flying'],ability:'tough-claws',bst:615,stone:'Mega Aerodactyl Stone',sdn:'aerodactylmega',fid:10042},
  {id:10053,name:'aggron',megaName:'Mega Aggron',types:['steel'],ability:'filter',bst:630,stone:'Mega Aggron Stone',sdn:'aggronmega',fid:10053},
  {id:10037,name:'alakazam',megaName:'Mega Alakazam',types:['psychic'],ability:'trace',bst:600,stone:'Mega Alakazam Stone',sdn:'alakazammega',fid:10037},
  {id:10067,name:'altaria',megaName:'Mega Altaria',types:['dragon','fairy'],ability:'pixilate',bst:590,stone:'Mega Altaria Stone',sdn:'altariamega',fid:10067},
  {id:10045,name:'ampharos',megaName:'Mega Ampharos',types:['electric','dragon'],ability:'mold-breaker',bst:610,stone:'Mega Ampharos Stone',sdn:'ampharosmega',fid:10045},
  {id:10069,name:'audino',megaName:'Mega Audino',types:['normal','fairy'],ability:'healer',bst:545,stone:'Mega Audino Stone',sdn:'audinomega',fid:10069},
  {id:10056,name:'banette',megaName:'Mega Banette',types:['ghost'],ability:'prankster',bst:555,stone:'Mega Banette Stone',sdn:'banettemega',fid:10056},
  {id:10298,name:'barbaracle',megaName:'Mega Barbaracle',types:['rock','fighting'],ability:'tough-claws',bst:600,stone:'Mega Barbaracle Stone',sdn:'barbaraclemega',fid:10298},
  {id:10325,name:'baxcalibur',megaName:'Mega Baxcalibur',types:['dragon','ice'],ability:'unknown',bst:700,stone:'Mega Baxcalibur Stone',sdn:'baxcaliburmega',fid:10325},
  {id:10090,name:'beedrill',megaName:'Mega Beedrill',types:['bug','poison'],ability:'adaptability',bst:495,stone:'Mega Beedrill Stone',sdn:'beedrillmega',fid:10090},
  {id:10036,name:'blastoise',megaName:'Mega Blastoise',types:['water'],ability:'mega-launcher',bst:630,stone:'Mega Blastoise Stone',sdn:'blastoisemega',fid:10036},
  {id:10050,name:'blaziken',megaName:'Mega Blaziken',types:['fire','fighting'],ability:'speed-boost',bst:630,stone:'Mega Blaziken Stone',sdn:'blazikenmega',fid:10050},
  {id:10087,name:'camerupt',megaName:'Mega Camerupt',types:['fire','ground'],ability:'sheer-force',bst:560,stone:'Mega Camerupt Stone',sdn:'cameruptmega',fid:10087},
  {id:10291,name:'chandelure',megaName:'Mega Chandelure',types:['ghost','fire'],ability:'infiltrator',bst:620,stone:'Mega Chandelure Stone',sdn:'chandeluremega',fid:10291},
  {id:10034,name:'charizard',megaName:'Mega Charizard X',types:['fire','dragon'],ability:'tough-claws',bst:634,stone:'Mega Charizard X Stone',sdn:'charizardmegax',fid:10034},
  {id:10035,name:'charizard',megaName:'Mega Charizard Y',types:['fire','flying'],ability:'drought',bst:634,stone:'Mega Charizard Y Stone',sdn:'charizardmegay',fid:10035},
  {id:10292,name:'chesnaught',megaName:'Mega Chesnaught',types:['grass','fighting'],ability:'bulletproof',bst:630,stone:'Mega Chesnaught Stone',sdn:'chesnaughtmega',fid:10292},
  {id:10306,name:'chimecho',megaName:'Mega Chimecho',types:['psychic','steel'],ability:'levitate',bst:555,stone:'Mega Chimecho Stone',sdn:'chimechomega',fid:10306},
  {id:10278,name:'clefable',megaName:'Mega Clefable',types:['fairy','flying'],ability:'magic-bounce',bst:583,stone:'Mega Clefable Stone',sdn:'clefablemega',fid:10278},
  {id:10315,name:'crabominable',megaName:'Mega Crabominable',types:['fighting','ice'],ability:'iron-fist',bst:578,stone:'Mega Crabominable Stone',sdn:'crabominablemega',fid:10315},
  {id:10312,name:'darkrai',megaName:'Mega Darkrai',types:['dark'],ability:'unknown',bst:700,stone:'Mega Darkrai Stone',sdn:'darkraimega',fid:10312},
  {id:10293,name:'delphox',megaName:'Mega Delphox',types:['fire','psychic'],ability:'levitate',bst:634,stone:'Mega Delphox Stone',sdn:'delphoxmega',fid:10293},
  {id:10075,name:'diancie',megaName:'Mega Diancie',types:['rock','fairy'],ability:'magic-bounce',bst:700,stone:'Mega Diancie Stone',sdn:'dianciemega',fid:10075},
  {id:10299,name:'dragalge',megaName:'Mega Dragalge',types:['poison','dragon'],ability:'regenerator',bst:594,stone:'Mega Dragalge Stone',sdn:'dragalgemega',fid:10299},
  {id:10281,name:'dragonite',megaName:'Mega Dragonite',types:['dragon','flying'],ability:'multiscale',bst:700,stone:'Mega Dragonite Stone',sdn:'dragonitemega',fid:10281},
  {id:10302,name:'drampa',megaName:'Mega Drampa',types:['normal','dragon'],ability:'berserk',bst:585,stone:'Mega Drampa Stone',sdn:'drampamega',fid:10302},
  {id:10290,name:'eelektross',megaName:'Mega Eelektross',types:['electric'],ability:'eelevate',bst:615,stone:'Mega Eelektross Stone',sdn:'eelektrossmega',fid:10290},
  {id:10286,name:'emboar',megaName:'Mega Emboar',types:['fire','fighting'],ability:'mold-breaker',bst:628,stone:'Mega Emboar Stone',sdn:'emboarmega',fid:10286},
  {id:10287,name:'excadrill',megaName:'Mega Excadrill',types:['ground','steel'],ability:'piercing-drill',bst:608,stone:'Mega Excadrill Stone',sdn:'excadrillmega',fid:10287},
  {id:10303,name:'falinks',megaName:'Mega Falinks',types:['fighting'],ability:'defiant',bst:570,stone:'Mega Falinks Stone',sdn:'falinksmega',fid:10303},
  {id:10283,name:'feraligatr',megaName:'Mega Feraligatr',types:['water','dragon'],ability:'dragonize',bst:630,stone:'Mega Feraligatr Stone',sdn:'feraligatrmega',fid:10283},
  {id:10296,name:'floette',megaName:'Mega Floette',types:['fairy'],ability:'fairy-aura',bst:651,stone:'Mega Floette Stone',sdn:'floettemega',fid:10296},
  {id:10285,name:'froslass',megaName:'Mega Froslass',types:['ice','ghost'],ability:'snow-warning',bst:580,stone:'Mega Froslass Stone',sdn:'froslassmega',fid:10285},
  {id:10068,name:'gallade',megaName:'Mega Gallade',types:['psychic','fighting'],ability:'inner-focus',bst:618,stone:'Mega Gallade Stone',sdn:'gallademega',fid:10068},
  {id:10058,name:'garchomp',megaName:'Mega Garchomp',types:['dragon','ground'],ability:'sand-force',bst:700,stone:'Mega Garchomp Stone',sdn:'garchompmega',fid:10058},
  {id:10309,name:'garchomp',megaName:'Mega Garchomp',types:['dragon'],ability:'unknown',bst:700,stone:'Mega Garchomp Stone',sdn:'garchompmega',fid:10309},
  {id:10051,name:'gardevoir',megaName:'Mega Gardevoir',types:['psychic','fairy'],ability:'pixilate',bst:618,stone:'Mega Gardevoir Stone',sdn:'gardevoirmega',fid:10051},
  {id:10038,name:'gengar',megaName:'Mega Gengar',types:['ghost','poison'],ability:'shadow-tag',bst:600,stone:'Mega Gengar Stone',sdn:'gengarmega',fid:10038},
  {id:10074,name:'glalie',megaName:'Mega Glalie',types:['ice'],ability:'refrigerate',bst:580,stone:'Mega Glalie Stone',sdn:'glaliemega',fid:10074},
  {id:10321,name:'glimmora',megaName:'Mega Glimmora',types:['rock','poison'],ability:'adaptability',bst:625,stone:'Mega Glimmora Stone',sdn:'glimmoramega',fid:10321},
  {id:10316,name:'golisopod',megaName:'Mega Golisopod',types:['bug','steel'],ability:'unknown',bst:630,stone:'Mega Golisopod Stone',sdn:'golisopodmega',fid:10316},
  {id:10313,name:'golurk',megaName:'Mega Golurk',types:['ground','ghost'],ability:'unseen-fist',bst:583,stone:'Mega Golurk Stone',sdn:'golurkmega',fid:10313},
  {id:10294,name:'greninja',megaName:'Mega Greninja',types:['water','dark'],ability:'protean',bst:630,stone:'Mega Greninja Stone',sdn:'greninjamega',fid:10294},
  {id:10041,name:'gyarados',megaName:'Mega Gyarados',types:['water','dark'],ability:'mold-breaker',bst:640,stone:'Mega Gyarados Stone',sdn:'gyaradosmega',fid:10041},
  {id:10300,name:'hawlucha',megaName:'Mega Hawlucha',types:['fighting','flying'],ability:'no-guard',bst:600,stone:'Mega Hawlucha Stone',sdn:'hawluchamega',fid:10300},
  {id:10311,name:'heatran',megaName:'Mega Heatran',types:['fire','steel'],ability:'unknown',bst:700,stone:'Mega Heatran Stone',sdn:'heatranmega',fid:10311},
  {id:10047,name:'heracross',megaName:'Mega Heracross',types:['bug','fighting'],ability:'skill-link',bst:600,stone:'Mega Heracross Stone',sdn:'heracrossmega',fid:10047},
  {id:10048,name:'houndoom',megaName:'Mega Houndoom',types:['dark','fire'],ability:'solar-power',bst:600,stone:'Mega Houndoom Stone',sdn:'houndoommega',fid:10048},
  {id:10039,name:'kangaskhan',megaName:'Mega Kangaskhan',types:['normal'],ability:'parental-bond',bst:590,stone:'Mega Kangaskhan Stone',sdn:'kangaskhanmega',fid:10039},
  {id:10062,name:'latias',megaName:'Mega Latias',types:['dragon','psychic'],ability:'levitate',bst:700,stone:'Mega Latias Stone',sdn:'latiasmega',fid:10062},
  {id:10063,name:'latios',megaName:'Mega Latios',types:['dragon','psychic'],ability:'levitate',bst:700,stone:'Mega Latios Stone',sdn:'latiosmega',fid:10063},
  {id:10088,name:'lopunny',megaName:'Mega Lopunny',types:['normal','fighting'],ability:'scrappy',bst:580,stone:'Mega Lopunny Stone',sdn:'lopunnymega',fid:10088},
  {id:10059,name:'lucario',megaName:'Mega Lucario',types:['fighting','steel'],ability:'adaptability',bst:625,stone:'Mega Lucario Stone',sdn:'lucariomega',fid:10059},
  {id:10310,name:'lucario',megaName:'Mega Lucario',types:['fighting','steel'],ability:'unknown',bst:625,stone:'Mega Lucario Stone',sdn:'lucariomega',fid:10310},
  {id:10317,name:'magearna',megaName:'Mega Magearna',types:['steel','fairy'],ability:'unknown',bst:700,stone:'Mega Magearna Stone',sdn:'magearnamega',fid:10317},
  {id:10318,name:'magearna',megaName:'Mega Magearna (Original)',types:['steel','fairy'],ability:'unknown',bst:700,stone:'Mega Magearna (Original) Stone',sdn:'magearnamega',fid:10318},
  {id:10297,name:'malamar',megaName:'Mega Malamar',types:['dark','psychic'],ability:'contrary',bst:582,stone:'Mega Malamar Stone',sdn:'malamarmega',fid:10297},
  {id:10055,name:'manectric',megaName:'Mega Manectric',types:['electric'],ability:'intimidate',bst:575,stone:'Mega Manectric Stone',sdn:'manectricmega',fid:10055},
  {id:10052,name:'mawile',megaName:'Mega Mawile',types:['steel','fairy'],ability:'huge-power',bst:480,stone:'Mega Mawile Stone',sdn:'mawilemega',fid:10052},
  {id:10054,name:'medicham',megaName:'Mega Medicham',types:['fighting','psychic'],ability:'pure-power',bst:510,stone:'Mega Medicham Stone',sdn:'medichammega',fid:10054},
  {id:10282,name:'meganium',megaName:'Mega Meganium',types:['grass','fairy'],ability:'mega-sol',bst:625,stone:'Mega Meganium Stone',sdn:'meganiummega',fid:10282},
  {id:10326,name:'meowstic',megaName:'Mega Meowstic (Female)',types:['psychic'],ability:'trace',bst:566,stone:'Mega Meowstic (Female) Stone',sdn:'meowsticmega',fid:10326},
  {id:10314,name:'meowstic',megaName:'Mega Meowstic (Male)',types:['psychic'],ability:'trace',bst:566,stone:'Mega Meowstic (Male) Stone',sdn:'meowsticmega',fid:10314},
  {id:10076,name:'metagross',megaName:'Mega Metagross',types:['steel','psychic'],ability:'tough-claws',bst:700,stone:'Mega Metagross Stone',sdn:'metagrossmega',fid:10076},
  {id:10043,name:'mewtwo',megaName:'Mega Mewtwo X',types:['psychic','fighting'],ability:'steadfast',bst:780,stone:'Mega Mewtwo X Stone',sdn:'mewtwomegax',fid:10043},
  {id:10044,name:'mewtwo',megaName:'Mega Mewtwo Y',types:['psychic'],ability:'insomnia',bst:780,stone:'Mega Mewtwo Y Stone',sdn:'mewtwomegay',fid:10044},
  {id:10073,name:'pidgeot',megaName:'Mega Pidgeot',types:['normal','flying'],ability:'no-guard',bst:579,stone:'Mega Pidgeot Stone',sdn:'pidgeotmega',fid:10073},
  {id:10040,name:'pinsir',megaName:'Mega Pinsir',types:['bug','flying'],ability:'aerilate',bst:600,stone:'Mega Pinsir Stone',sdn:'pinsirmega',fid:10040},
  {id:10295,name:'pyroar',megaName:'Mega Pyroar',types:['fire','normal'],ability:'fire-mane',bst:607,stone:'Mega Pyroar Stone',sdn:'pyroarmega',fid:10295},
  {id:10304,name:'raichu',megaName:'Mega Raichu X',types:['electric'],ability:'electric-surge',bst:585,stone:'Mega Raichu X Stone',sdn:'raichumegax',fid:10304},
  {id:10305,name:'raichu',megaName:'Mega Raichu Y',types:['electric'],ability:'no-guard',bst:585,stone:'Mega Raichu Y Stone',sdn:'raichumegay',fid:10305},
  {id:10079,name:'rayquaza',megaName:'Mega Rayquaza',types:['dragon','flying'],ability:'delta-stream',bst:780,stone:'Mega Rayquaza Stone',sdn:'rayquazamega',fid:10079},
  {id:10066,name:'sableye',megaName:'Mega Sableye',types:['dark','ghost'],ability:'magic-bounce',bst:480,stone:'Mega Sableye Stone',sdn:'sableyemega',fid:10066},
  {id:10089,name:'salamence',megaName:'Mega Salamence',types:['dragon','flying'],ability:'aerilate',bst:700,stone:'Mega Salamence Stone',sdn:'salamencemega',fid:10089},
  {id:10065,name:'sceptile',megaName:'Mega Sceptile',types:['grass','dragon'],ability:'lightning-rod',bst:630,stone:'Mega Sceptile Stone',sdn:'sceptilemega',fid:10065},
  {id:10046,name:'scizor',megaName:'Mega Scizor',types:['bug','steel'],ability:'technician',bst:600,stone:'Mega Scizor Stone',sdn:'scizormega',fid:10046},
  {id:10288,name:'scolipede',megaName:'Mega Scolipede',types:['bug','poison'],ability:'shell-armor',bst:585,stone:'Mega Scolipede Stone',sdn:'scolipedemega',fid:10288},
  {id:10320,name:'scovillain',megaName:'Mega Scovillain',types:['grass','fire'],ability:'spicy-spray',bst:586,stone:'Mega Scovillain Stone',sdn:'scovillainmega',fid:10320},
  {id:10289,name:'scrafty',megaName:'Mega Scrafty',types:['dark','fighting'],ability:'intimidate',bst:588,stone:'Mega Scrafty Stone',sdn:'scraftymega',fid:10289},
  {id:10070,name:'sharpedo',megaName:'Mega Sharpedo',types:['water','dark'],ability:'strong-jaw',bst:560,stone:'Mega Sharpedo Stone',sdn:'sharpedomega',fid:10070},
  {id:10284,name:'skarmory',megaName:'Mega Skarmory',types:['steel','flying'],ability:'stalwart',bst:565,stone:'Mega Skarmory Stone',sdn:'skarmorymega',fid:10284},
  {id:10071,name:'slowbro',megaName:'Mega Slowbro',types:['water','psychic'],ability:'shell-armor',bst:590,stone:'Mega Slowbro Stone',sdn:'slowbromega',fid:10071},
  {id:10308,name:'staraptor',megaName:'Mega Staraptor',types:['fighting','flying'],ability:'contrary',bst:585,stone:'Mega Staraptor Stone',sdn:'staraptormega',fid:10308},
  {id:10280,name:'starmie',megaName:'Mega Starmie',types:['water','psychic'],ability:'huge-power',bst:620,stone:'Mega Starmie Stone',sdn:'starmiemega',fid:10280},
  {id:10072,name:'steelix',megaName:'Mega Steelix',types:['steel','ground'],ability:'sand-force',bst:610,stone:'Mega Steelix Stone',sdn:'steelixmega',fid:10072},
  {id:10064,name:'swampert',megaName:'Mega Swampert',types:['water','ground'],ability:'swift-swim',bst:635,stone:'Mega Swampert Stone',sdn:'swampertmega',fid:10064},
  {id:10322,name:'tatsugiri',megaName:'Mega Tatsugiri',types:['dragon','water'],ability:'unknown',bst:575,stone:'Mega Tatsugiri Stone',sdn:'tatsugirimega',fid:10322},
  {id:10323,name:'tatsugiri',megaName:'Mega Tatsugiri',types:['dragon','water'],ability:'unknown',bst:575,stone:'Mega Tatsugiri Stone',sdn:'tatsugirimega',fid:10323},
  {id:10324,name:'tatsugiri',megaName:'Mega Tatsugiri',types:['dragon','water'],ability:'unknown',bst:575,stone:'Mega Tatsugiri Stone',sdn:'tatsugirimega',fid:10324},
  {id:10049,name:'tyranitar',megaName:'Mega Tyranitar',types:['rock','dark'],ability:'sand-stream',bst:700,stone:'Mega Tyranitar Stone',sdn:'tyranitarmega',fid:10049},
  {id:10033,name:'venusaur',megaName:'Mega Venusaur',types:['grass','poison'],ability:'thick-fat',bst:625,stone:'Mega Venusaur Stone',sdn:'venusaurmega',fid:10033},
  {id:10279,name:'victreebel',megaName:'Mega Victreebel',types:['grass','poison'],ability:'innards-out',bst:590,stone:'Mega Victreebel Stone',sdn:'victreebelmega',fid:10279},
  {id:10319,name:'zeraora',megaName:'Mega Zeraora',types:['electric'],ability:'unknown',bst:700,stone:'Mega Zeraora Stone',sdn:'zeraoramega',fid:10319},
  {id:10301,name:'zygarde',megaName:'Mega Zygarde',types:['dragon','ground'],ability:'unknown',bst:778,stone:'Mega Zygarde Stone',sdn:'zygardemega',fid:10301}
];
